<?php
require_once __DIR__ . '/../Services/DemoSyntheticCallCollection.php';
require_once __DIR__ . '/../Services/HistoricalResultFloor.php';
if (!interface_exists('BMO')) { interface BMO {} }
require_once __DIR__ . '/../Concurrencycount.class.php';
use FreePBX\modules\Concurrencycount\Services\DemoSyntheticCallCollection;
use FreePBX\modules\Concurrencycount\Services\HistoricalResultFloor;
function synthetic_assert($condition,string $message):void{if(!$condition)throw new Exception($message);}
function synthetic_private($object,string $name){$property=new ReflectionProperty($object,$name);$property->setAccessible(true);return $property->getValue($object);}
function synthetic_row(int $index,string $channel='PJSIP/101-a1b2c3d4'):array{return ['calldate'=>'2026-09-12 10:00:00','answer'=>'2026-09-12 10:00:16','duration'=>61+$index,'billsec'=>45,'src'=>'101','dst'=>'5550001','did'=>'2125550100','disposition'=>$index?'NO ANSWER':'ANSWERED','channel'=>$channel,'dstchannel'=>'PJSIP/target-aabbccdd','accountcode'=>'CCDEMO1234abcd','lastapp'=>'Dial','lastdata'=>'PJSIP/carrier/5550001','dcontext'=>'from-internal','carrier'=>'MAGRATHEA-IN-1','hangupsource'=>$channel,'hangupcause'=>16,'recordingfile'=>'demo.wav','_direction'=>'outbound','_flow'=>'outbound-local','_trunk'=>'MAGRATHEA-IN-1','_handled_extension'=>'101','_extensions'=>['101']];}
$directory=sys_get_temp_dir().'/cc-audit-test-'.bin2hex(random_bytes(8));mkdir($directory,0700,true);$owner=hash('sha256','test-session');
try{
	$writeAll=new ReflectionMethod(DemoSyntheticCallCollection::class,'writeAll');$writeAll->setAccessible(true);$writeTarget=fopen('php://temp','w+b');$writePayload=str_repeat('complete-write-',1000);synthetic_assert($writeAll->invoke(null,$writeTarget,$writePayload)===true,'The complete-write helper must report success');rewind($writeTarget);synthetic_assert(stream_get_contents($writeTarget)===$writePayload,'The complete-write helper must persist every supplied byte');fclose($writeTarget);
	$collision=new DemoSyntheticCallCollection($owner,$directory);$collision->record(synthetic_row(0),'extension');$collisionPath=synthetic_private($collision,'path');$collisionMeta=preg_replace('/\.jsonl$/','.meta',$collisionPath);file_put_contents($collisionMeta,'do-not-overwrite');chmod($collisionMeta,0600);$collisionRejected=false;try{$collision->finalize();}catch(RuntimeException $expected){$collisionRejected=true;}synthetic_assert($collisionRejected&&file_get_contents($collisionMeta)==='do-not-overwrite','A pre-existing metadata file must be preserved and finalisation must fail closed');unlink($collisionMeta);
	$symlinkTarget=$directory.'/symlink-target';file_put_contents($symlinkTarget,'do-not-follow');chmod($symlinkTarget,0600);$symlinkCollision=new DemoSyntheticCallCollection($owner,$directory);$symlinkCollision->record(synthetic_row(0),'extension');$symlinkMeta=preg_replace('/\.jsonl$/','.meta',synthetic_private($symlinkCollision,'path'));symlink($symlinkTarget,$symlinkMeta);$symlinkRejected=false;try{$symlinkCollision->finalize();}catch(RuntimeException $expected){$symlinkRejected=true;}synthetic_assert($symlinkRejected&&file_get_contents($symlinkTarget)==='do-not-follow'&&is_link($symlinkMeta),'A metadata symlink must never be followed or replaced');unlink($symlinkMeta);unlink($symlinkTarget);
	$unsafe=$directory.'-unsafe';mkdir($unsafe,0777);chmod($unsafe,0777);$unsafeRejected=false;try{new DemoSyntheticCallCollection($owner,$unsafe);}catch(RuntimeException $expected){$unsafeRejected=true;}synthetic_assert($unsafeRejected,'A world-accessible spool directory must fail closed');rmdir($unsafe);
	$target=$directory.'-target';mkdir($target,0700);$link=$directory.'-link';symlink($target,$link);$linkRejected=false;try{new DemoSyntheticCallCollection($owner,$link);}catch(RuntimeException $expected){$linkRejected=true;}synthetic_assert($linkRejected,'A symlink spool directory must fail closed');unlink($link);rmdir($target);
	$partial=new DemoSyntheticCallCollection($owner,$directory);$partial->record(synthetic_row(0),'extension');$partialPath=synthetic_private($partial,'path');try{throw new RuntimeException('simulated cancellation');}catch(RuntimeException $expected){}finally{$partial->discard();}synthetic_assert(!file_exists($partialPath),'Cancellation after committed audit rows must discard the partial spool immediately');
	$cleanupFailure=new DemoSyntheticCallCollection($owner,$directory);$cleanupFailure->record(synthetic_row(0),'extension');$cleanupPage=$cleanupFailure->finalize();try{throw new RuntimeException('simulated mandatory cleanup failure');}catch(RuntimeException $expected){}finally{$cleanupFailure->discard();}$cleanupUnavailable=false;try{DemoSyntheticCallCollection::fetchPage($cleanupPage['token'],$owner,1,$directory);}catch(RuntimeException $expected){$cleanupUnavailable=true;}synthetic_assert($cleanupUnavailable,'Mandatory cleanup failure must discard even a finalized audit spool');
 foreach(['trunk'=>'MAGRATHEA-IN-1','extension'=>'101','group'=>'PBX-wide group (101)'] as $mode=>$identity){$collection=new DemoSyntheticCallCollection($owner,$directory);$row=synthetic_row(0,$mode==='trunk'?'PJSIP/MAGRATHEA-IN-1-a1b2c3d4':'PJSIP/101-a1b2c3d4');$collection->record($row,$mode);$page=$collection->finalize();$call=$page['items'][0];synthetic_assert($page['total']===1&&$call['report_identity']===$identity,ucfirst($mode).' audit identity changed');synthetic_assert($call['start']===$row['calldate']&&$call['end']==='2026-09-12 10:01:01'&&$call['duration']===61,'Audit timing must remain exact');$collection->discard();}
 $heavy=new DemoSyntheticCallCollection($owner,$directory);for($i=0;$i<20000;$i++)$heavy->record(synthetic_row($i),'extension');$mix=$heavy->trafficMix();$first=$heavy->finalize();
 synthetic_assert($heavy->count()===20000&&$first['total']===20000&&count($first['items'])===100,'Heavy result must expose totals but only its bounded first page');
 synthetic_assert(!method_exists($heavy,'all'),'Audit service must not retain/expose a full in-memory call collection');
 $last=DemoSyntheticCallCollection::fetchPage($first['token'],$owner,200,$directory);synthetic_assert(count($last['items'])===100&&$last['page']===200,'Every server page must contain at most 100 calls');
 synthetic_assert(array_sum($mix['directions'])===20000&&array_sum($mix['dispositions'])===20000,'Traffic mix must accumulate independently from detail paging');
 synthetic_assert($heavy->integrity(20000,20000,20000,0)==='verified'&&$heavy->integrity(20000,20000,19999,1)==='mismatch','Integrity counts must remain independent from displayed pages');
 try{DemoSyntheticCallCollection::fetchPage($first['token'],'wrong-owner',1,$directory);throw new Exception('Wrong owner accepted');}catch(RuntimeException $expected){}
	$floored=(new HistoricalResultFloor())->apply(['mode'=>'demo','global_max'=>5,'synthetic_calls_page'=>$first],6);synthetic_assert(count($floored['synthetic_calls_page']['items'])===100,'Minimum concurrency must not filter audit pages');
	if (session_status() !== PHP_SESSION_ACTIVE) { session_id('ccdemoreviewtest'); session_start(); }
	$endpointOwner=hash('sha256','concurrencycount-gui:'.session_id());$endpointCollection=new DemoSyntheticCallCollection($endpointOwner);$endpointCollection->record(synthetic_row(0),'extension');$completedPage=$endpointCollection->finalize();
	$_REQUEST=['audit_token'=>$completedPage['token'],'page'=>1];$endpointModule=(new ReflectionClass(\FreePBX\modules\Concurrencycount::class))->newInstanceWithoutConstructor();$endpointMethod=new ReflectionMethod($endpointModule,'handleDemoCallPage');$endpointMethod->setAccessible(true);$endpointResponse=$endpointMethod->invoke($endpointModule);
	synthetic_assert($endpointResponse['status']===true&&$endpointResponse['audit']['total']===1&&$endpointResponse['audit']['items'][0]['accountcode']!=='','The completed-run review token must remain reachable through handleDemoCallPage');$endpointCollection->discard();
	$heavy->discard();synthetic_assert(count(glob($directory.'/*'))===0,'Discard must remove transient paging state');
}finally{foreach((array)glob($directory.'/*') as $file)@unlink($file);@rmdir($directory);}
echo "Demo synthetic call collection tests passed\n";
