'use strict';
const fs=require('fs');
const order=require('../assets/js/cc-historical-report-order.js');
function assert(value,message){if(!value)throw new Error(message);}
const original=['stable-1','stable-2','stable-3'];
assert(order.move(original,'stable-2',-1).join(',')==='stable-2,stable-1,stable-3'&&original.join(',')==='stable-1,stable-2,stable-3','Keyboard movement preserves stable identities without mutating source state');
assert(order.drop(original,'stable-3','stable-1',false).join(',')==='stable-3,stable-1,stable-2','Handle drop inserts exactly before its target');
assert(order.drop(original,'stable-1','stable-3',true).join(',')==='stable-2,stable-3,stable-1','Handle drop inserts exactly after its target');
assert(order.drop(original,'stable-1','stable-1',false).join(',')===original.join(','),'Dropping the first tab onto itself before is unchanged');
assert(order.drop(original,'stable-1','stable-1',true).join(',')===original.join(','),'Dropping the first tab onto itself after is unchanged');
assert(order.drop(original,'stable-2','stable-2',false).join(',')===original.join(','),'Dropping a middle tab onto itself before is unchanged');
assert(order.drop(original,'stable-2','stable-2',true).join(',')===original.join(','),'Dropping a middle tab onto itself after is unchanged');
let sends=[],callbacks=[],saved=[];
const saver=order.createSaver(function(value,done){sends.push(value.join(','));callbacks.push(done);},function(value){saved.push(value.join(','));},function(){throw new Error('Unexpected save failure');});
saver.request(['stable-1','stable-2','stable-3']);saver.request(['stable-2','stable-1','stable-3']);saver.request(['stable-3','stable-2','stable-1']);
assert(sends.length===1&&saver.isBusy(),'Rapid moves serialize the first persistence request');
callbacks.shift()(null,{status:true});
assert(sends.length===2&&sends[1]==='stable-3,stable-2,stable-1','Rapid sequence coalesces to and persists the final visible order');
callbacks.shift()(null,{status:true});
assert(saved[saved.length-1]==='stable-3,stable-2,stable-1'&&!saver.isBusy(),'Final visible order is the final confirmed order');
let failureSends=[],failureCallbacks=[],failures=[];
const failureSaver=order.createSaver(function(value,done,context){failureSends.push(value.join(',')+':'+context);failureCallbacks.push(done);},function(){},function(message,value,context){failures.push(message+':'+value.join(',')+':'+context);});
failureSaver.request(['stable-1','stable-2'],1);
failureSaver.request(['stable-2','stable-1'],2);
failureCallbacks.shift()('Rejected stale order.');
assert(failures[0]==='Rejected stale order.:stable-1,stable-2:1','Failed recovery retains the exact failed request generation');
assert(failureSends.join('|')==='stable-1,stable-2:1|stable-2,stable-1:2'&&failureSaver.isBusy(),'A newer queued reorder is preserved and sent after an older save fails');
failureCallbacks.shift()(null,{status:true});
assert(!failureSaver.isBusy(),'Queued reorder persistence settles after the newer save succeeds');
const cached={id:'stable-1',name:'Old name',result:{peak:4},hasRun:true,occurrenceCache:{'0:0':{expanded:true}},graphSeries:[1,2]};
const removed={id:'stable-2',result:{peak:2},hasRun:true,occurrenceCache:{},graphSeries:[3]};
const reconciled=order.reconcileInventory({'stable-1':cached,'stable-2':removed},[{id:'stable-3',name:'Remote report',number:3},{id:'stable-1',name:'Authoritative name',number:1}],'stable-2');
assert(reconciled.order.join(',')==='stable-3,stable-1'&&reconciled.reports['stable-3'].name==='Remote report','Authoritative reconciliation adds remote reports in server order');
assert(!reconciled.reports['stable-2']&&reconciled.activeRemoved&&reconciled.fallbackId==='stable-3','Authoritative reconciliation removes remote closes and provides a safe active fallback');
assert(reconciled.reports['stable-1'].name==='Authoritative name'&&reconciled.reports['stable-1'].result===cached.result&&reconciled.reports['stable-1'].occurrenceCache===cached.occurrenceCache&&reconciled.reports['stable-1'].graphSeries===cached.graphSeries,'Surviving reports retain transient result, occurrence and graph caches while accepting server definitions');
const guard=order.createGenerationGuard(),recoveryGeneration=guard.current();
guard.advance();
assert(!guard.isCurrent(recoveryGeneration),'A recovery response started before a newer mutation is stale');
const currentGeneration=guard.current();
assert(guard.isCurrent(currentGeneration),'The current recovery generation remains applicable');
const controller=fs.readFileSync(require.resolve('../assets/js/concurrencycount.js'),'utf8');
const activation=controller.match(/function activateReportTab\(id\) \{([\s\S]*?)\n\t\}/);
assert(activation&&!/historicalMutationGuard\.advance\(\)/.test(activation[1]),'Activating a report tab does not invalidate in-flight authoritative recovery');
let recoveryStateGeneration=0,recoveryCallbacks=[],applied=[];
const recovery=order.createRecovery(function(done){recoveryCallbacks.push(done);},function(){return recoveryStateGeneration;},function(response){applied.push(response.version);});
recovery.request(recoveryStateGeneration);
recoveryCallbacks.shift()(null,{status:true,version:'after-activation'});
assert(applied.join(',')==='after-activation'&&!recovery.isBusy(),'Recovery still applies when presentation-only tab activation occurs before its response');
recovery.request(recoveryStateGeneration);
recoveryStateGeneration++;
recoveryCallbacks.shift()(null,{status:true,version:'stale'});
assert(applied.join(',')==='after-activation'&&recoveryCallbacks.length===1&&recovery.isBusy(),'A genuine newer mutation discards stale recovery and starts one fresh authoritative read');
recoveryCallbacks.shift()(null,{status:true,version:'fresh'});
assert(applied.join(',')==='after-activation,fresh'&&!recovery.isBusy(),'Fresh recovery applies after the newer mutation so local state eventually converges');
let raceGeneration=1,raceVisible=['stable-2','stable-1'],raceConfirmed=[],raceSaveCallbacks=[],raceRecoveryCallbacks=[];
const raceReports={'stable-1':{id:'stable-1'},'stable-2':{id:'stable-2'}};
const raceRecovery=order.createRecovery(function(done){raceRecoveryCallbacks.push(done);},function(){return raceGeneration;},function(response){raceVisible=response.order.slice();});
const raceSaver=order.createSaver(function(value,done){raceSaveCallbacks.push(done);},function(value,response,generation){
	raceConfirmed=value.slice();
	if(generation===raceGeneration){raceVisible=order.restorePersistedOrder(value,raceVisible,raceReports);raceGeneration++;}
},function(message,value,generation){raceRecovery.request(generation);});
raceSaver.request(['stable-1','stable-2'],raceGeneration);
raceGeneration++;
raceVisible=['stable-2','stable-1'];
raceSaver.request(raceVisible,raceGeneration);
raceSaveCallbacks.shift()('Rejected stale order.');
assert(raceSaveCallbacks.length===1&&raceRecoveryCallbacks.length===1,'A failure starts recovery while queued B is sent');
raceRecoveryCallbacks.shift()(null,{status:true,order:['stable-1','stable-2']});
assert(raceRecoveryCallbacks.length===1,'Stale recovery A starts a fresh recovery at B generation');
raceRecoveryCallbacks.shift()(null,{status:true,order:['stable-1','stable-2']});
assert(raceVisible.join(',')==='stable-1,stable-2','Fresh recovery may apply the older server order before B completes');
raceSaveCallbacks.shift()(null,{status:true});
assert(raceConfirmed.join(',')==='stable-2,stable-1'&&raceVisible.join(',')==='stable-2,stable-1','Current-generation B success restores the final visible local order to the successfully persisted order');
raceGeneration++;
raceVisible=['stable-1','stable-2'];
raceSaver.request(['stable-2','stable-1'],raceGeneration-1);
raceSaveCallbacks.shift()(null,{status:true});
assert(raceVisible.join(',')==='stable-1,stable-2','A successful older save cannot overwrite a genuinely newer local reorder');
let delayedGeneration=1,delayedVisible=['stable-2','stable-1'],delayedSaveCallbacks=[],delayedRecoveryCallbacks=[];
const delayedRecovery=order.createRecovery(function(done){delayedRecoveryCallbacks.push(done);},function(){return delayedGeneration;},function(response){delayedVisible=response.order.slice();});
const delayedSaver=order.createSaver(function(value,done){delayedSaveCallbacks.push(done);},function(value,response,generation){
	if(generation===delayedGeneration){delayedVisible=order.restorePersistedOrder(value,delayedVisible,raceReports);delayedGeneration++;}
},function(message,value,generation){delayedRecovery.request(generation);});
delayedSaver.request(['stable-1','stable-2'],delayedGeneration);
delayedGeneration++;
delayedVisible=['stable-2','stable-1'];
delayedSaver.request(delayedVisible,delayedGeneration);
delayedSaveCallbacks.shift()('Rejected stale order.');
delayedRecoveryCallbacks.shift()(null,{status:true,order:['stable-1','stable-2']});
assert(delayedRecoveryCallbacks.length===1&&delayedSaver.isBusy(),'Stale recovery A starts recovery B while the newer save remains in flight');
delayedSaveCallbacks.shift()(null,{status:true});
assert(delayedVisible.join(',')==='stable-2,stable-1','Current-generation B success restores B before delayed recovery B returns');
delayedRecoveryCallbacks.shift()(null,{status:true,order:['stable-1','stable-2']});
assert(delayedVisible.join(',')==='stable-2,stable-1'&&delayedRecoveryCallbacks.length===1&&delayedRecovery.isBusy(),'Delayed recovery B is stale after successful persistence and schedules one fresh authoritative read');
delayedRecoveryCallbacks.shift()(null,{status:true,order:['stable-2','stable-1']});
assert(delayedVisible.join(',')==='stable-2,stable-1'&&!delayedRecovery.isBusy(),'Fresh post-persistence recovery converges without changing the persisted B order');
assert(order.restorePersistedOrder(['stable-2','removed'],['remote','stable-1','stable-2'],{'remote':{},'stable-1':{},'stable-2':{}}).join(',')==='stable-2,remote,stable-1','Persisted-order restoration preserves remote creates and omits remote deletes');
console.log('Historical report order tests passed');
